CC=gcc

all: task1 task2
	
task1: task1-1 task1-2 task1-3 task1-4
task2: task2-1 task2-2

task1-1:
	$(CC) task1_1.c -o task1_1

task1-2:
	chmod u+x task1_2 

task1-3:
	$(CC) task1_3.c -o task1_3

task1-4:
	chmod u+x task1_4

task2-1:
	$(CC) task2_1.c -o task2_1

task2-2:
	$(CC) task2_2.c -o task2_2

clean:
	rm flag.txt
	rm meow.zip