all:
	chmod +x ./attack_main
	chmod +x ./attacker_server
	chmod +x ./crack_attack

copy:
	cp ./catv ./catv.copy
	cp ./catw ./catw.copy
	cp ./crack_attack ./crack_attack.copy
	cp ./attack_main ./attack_main.copy
	cp ./attacker_server ./attacker_server.copy

clean:
	rm ./cat.gz
	rm ./infected_cat
	rm ./catv_tmp
